### ISSUE TITLE
Origin/license for the USB-C connector symbol/footprint

### ISSUE THREAD

**Issue by piit79** [coseyfannitutti/discipline#34]
Hi @coseyfannitutti, could you please let me know what's the origin/license of the USB4085-GF-A USB-C connector KiCad schematic symbol and footprint used in Discipline? I managed to replace the Mini USB connector on the [Plaid](https://github.com/hsgw/plaid) with this connector (https://github.com/hsgw/plaid/pull/27), but I'm not sure it's OK to use the schematic symbol/footprint and commit it into the Plaid repo.

Thanks a lot!

**Comment by coseyfannitutti** [comment]
The USB4085-GF-A footprint that I use is a modified version of the one that was in ai03's USB Type-C library. The symbol I just made myself because at the time his library didn't include one, and I wanted to be sure that the pins would be assigned correctly.

It is absolutely fine for you to use them for Plaid.

**Comment by piit79** [comment]
Thanks, much appreciated!
