### ISSUE TITLE
Micro USB-C alternatives USB4085-GF-A

### ISSUE THREAD

**Issue by jesusignazio** [coseyfannitutti/discipline#36]
The micro USB from the BOM is very hard to find. There is only stock on digikey and the shipping costs are very expensive.

I ordered a very similar one from Aliexpress (https://es.aliexpress.com/item/4000966998955.html) but it doesn't fit well.

**Comment by ClumsyPenguin** [comment]
@jesusignazio i ordered the ones you linked from aliexpress and those fit pretty well actually. The usb pins do not go deep enough, but i easily fixed by just soldering them do not worry about shorts yet just add loads of solder and then fix the shorts with solder whick. It works pretty good that way.
